# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGIfRSCWdeCCpfqqizwWshQSVlUunaJd
"""



import streamlit as st
import pandas as pd

st.set_page_config(page_title="High-End Phone Finder", layout="wide")

@st.cache_data
def load_data():
    return pd.read_csv("phones_with_tier.csv")

df = load_data()

st.title("📱 High-End Smartphone Finder")

# -------------------------
# Filters
# -------------------------

brands = ["All"] + sorted(df["brand_name"].fillna('').astype(str).unique().tolist())

brand = st.selectbox("Brand", brands)
year_range = st.slider("Release Year", 2018, 2026, (2022, 2026))
ram_min = st.slider("Min RAM (GB)", 0, 24, 8)
refresh_min = st.slider("Min Refresh Rate", 60, 165, 120)

filtered = df.copy()

filtered = filtered[
    (filtered.release_year >= year_range[0]) &
    (filtered.release_year <= year_range[1]) &
    (filtered.is_high_end == True) &
    (filtered.ram_capacity >= ram_min) &
    (filtered.refresh_rate >= refresh_min)
]

if brand != "All":
    filtered = filtered[filtered.brand_name == brand]

st.write(f"### Results: {len(filtered)} phones")

st.dataframe(
    filtered[[
        "brand_name",
        "model",
        "release_year",
        "processor_name",
        "ram_capacity",
        "battery_capacity",
        "refresh_rate"
    ]]
)

