# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGIfRSCWdeCCpfqqizwWshQSVlUunaJd
"""



import streamlit as st
import pandas as pd
import os

st.set_page_config(page_title="📱 High-End Phone Finder", layout="wide")

# -------------------------
# Load data safely
# -------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("phones_with_tier.csv", low_memory=False)

    # ensure numeric
    for col in ["release_year", "ram_capacity", "refresh_rate"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


df = load_data()

st.title("📱 High-End Smartphone Finder")

st.write("Dataset loaded:", df.shape)  # debug safety

# -------------------------
# Filters
# -------------------------

brands = ["All"] + sorted(df["brand_name"].dropna().unique())

brand = st.selectbox("Brand", brands)

# Handle potential NaN values in 'release_year'
valid_release_years = df['release_year'].dropna()

if not valid_release_years.empty:
    min_release_year = int(valid_release_years.min())
    max_release_year = int(valid_release_years.max())
else:
    # Fallback if no valid release years are found in the data
    min_release_year = 2000 # Sensible default for old phones
    max_release_year = 2024 # A recent sensible default

# Ensure the default slider values are within the calculated min/max
# and provide reasonable defaults if 2022-2026 range is problematic with actual data
default_slider_start = max(min_release_year, 2022)
default_slider_end = min(max_release_year, 2026)

# Adjust if the default range becomes inverted or nonsensical due to data limits
if default_slider_start > default_slider_end:
    default_slider_start = min_release_year
    default_slider_end = max_release_year

year_range = st.slider(
    "Release Year",
    min_release_year,
    max_release_year,
    (default_slider_start, default_slider_end)
)

tier_only = st.checkbox("High-end only", value=True)

ram_min = st.slider("Min RAM (GB)", 0, 24, 0)
refresh_min = st.slider("Min Refresh Rate", 60, 165, 60)

# -------------------------
# Filtering logic
# -------------------------

filtered = df.copy()

filtered = filtered[
    (filtered.release_year >= year_range[0]) &
    (filtered.release_year <= year_range[1])
]

if tier_only:
    filtered = filtered[filtered.is_high_end == True]

if brand != "All":
    filtered = filtered[filtered.brand_name == brand]

filtered = filtered[
    (filtered.ram_capacity >= ram_min) &
    (filtered.refresh_rate >= refresh_min)
]

# -------------------------
# Display
# -------------------------

st.success(f"Found {len(filtered)} phones")

st.dataframe(
    filtered[[
        "brand_name",
        "model",
        "release_year",
        "processor_name",
        "ram_capacity",
        "battery_capacity",
        "refresh_rate"
    ]],
    use_container_width=True
)

