# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1totTLBBQ0tyrivig1O2gXNWGrAyEK7Tl
"""

import pandas as pd

df = pd.read_csv("phones.csv", engine='python')

chip_keywords = [
    "Snapdragon 8",
    "Dimensity 9",
    "Apple A",
    "Tensor"
]

def is_high_end(row):
    chipset = str(row["processor_name"])
    ram = row["ram_capacity"]
    refresh = row["refresh_rate"]

    flagship = any(k in chipset for k in chip_keywords)

    return flagship and (ram >= 8 or refresh >= 120)

df["is_high_end"] = df.apply(is_high_end, axis=1)

df.to_csv("phones_with_tier.csv", index=False)

