# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1totTLBBQ0tyrivig1O2gXNWGrAyEK7Tl
"""

import pandas as pd

df = pd.read_csv("phones.csv", low_memory=False)

# -------------------------
# Clean numeric columns
# -------------------------
for col in ["release_year", "ram_capacity", "refresh_rate", "battery_capacity"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# -------------------------
# High-end classifier
# -------------------------
chip_keywords = [
    "Snapdragon 8",
    "Dimensity 9",
    "Apple A",
    "Tensor"
]

def is_high_end(row):
    chipset = str(row["processor_name"])

    return any(k in chipset for k in chip_keywords)


df["is_high_end"] = df.apply(is_high_end, axis=1)

print("Total phones:", len(df))
print("High-end phones:", df["is_high_end"].sum())

df.to_csv("phones_with_tier.csv", index=False)

